config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    devise_scope :user do
      root to: "devise/sessions#new"
    end
 
    #Route Admin
    namespace :admins do
      get 'dashboard' => 'pages#index'
      resources :nama_keluargas, except: [:destroy]
      resources :anggota_keluargas_imports, only: [:new, :create]
      resources :anggota_keluargas do
        collection do
          get 'pkb'
          get 'wki'
          get 'pemuda'
          get 'remaja'
          get 'asm'
          get 'template'
        end
        member do
          patch 'set_meninggal'
        end
      end
      resources :users, only: [:edit,:update] do
        member do
          patch 'change_password'
        end
      end
      resources :koloms
      resources :keuangans
      get 'meninggal_tahun_ini' => 'data_lain_lains#meninggal_tahun_ini'
      get 'lahir_tahun_ini' => 'data_lain_lains#lahir_tahun_ini'
      get 'ulang_tahun_minggu_depan' => 'data_lain_lains#ulang_tahun_minggu_depan'
      get 'ulang_tahun_minggu_ini' => 'data_lain_lains#ulang_tahun_minggu_ini'
      
    end

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/nama_keluarga.rb
# == Schema Information
#
# Table name: nama_keluargas
#
#  id                           :bigint           not null, primary key
#  active                       :boolean          default(TRUE)
#  kolom                        :string
#  nama                         :string
#  nomor_kartu_keluarga         :string
#  tanggal_pernikahan           :date
#  ulang_tahun_pernikahan_aktif :boolean          default(TRUE)
#  created_at                   :datetime         not null
#  updated_at                   :datetime         not null
#
class NamaKeluarga < ApplicationRecord
  has_many :anggota_keluargas
  # after_update :cek_ulang_tahun_pernikahan
  #Validasi
  validates :nama, :presence => true,
    :on => [:update, :create]
  validates :kolom, :presence => true,
    :on => [:update, :create]
  accepts_nested_attributes_for :anggota_keluargas, :reject_if => :all_blank, allow_destroy: true

  scope :ulang_tahun, ->(mulai_bulan, selesai_bulan, mulai_tanggal, selesai_tanggal){where("EXTRACT(month FROM tanggal_pernikahan) >= ? AND EXTRACT(month FROM tanggal_pernikahan) <= ? AND EXTRACT(day FROM tanggal_pernikahan) >= ? AND EXTRACT(day FROM tanggal_pernikahan) <= ?  and ulang_tahun_pernikahan_aktif = ? and active = ?",mulai_bulan,selesai_bulan,mulai_tanggal,selesai_tanggal,true,true )}


  def daftar_ulang_tahun_pernikahan
    if self.anggota_keluargas.where(meninggal: false).pluck(:status_hubungan).exclude? ('kepala_keluarga') or self.anggota_keluargas.pluck(:status_hubungan).exclude? ('istri')
      self.update(ulang_tahun_pernikahan_aktif: false)
    else
      self.update(ulang_tahun_pernikahan_aktif: true)
    end
  end

  def umur_pernikahan
    now = Date.today
    now.year - tanggal_pernikahan.year - ((now.month > tanggal_pernikahan.month || (now.month == tanggal_pernikahan.month && now.day >= tanggal_pernikahan.day)) ? 0 : 1)
  end
end

app/controllers/admins/nama_keluargas_controller.rb
class Admins::NamaKeluargasController < AdminsController
  before_action :set_nama_keluarga, except: [:index, :new, :create]

  def index
    @q = NamaKeluarga.where(active:true).order('kolom::integer asc').ransack(params[:q])
		@pagy, @nama_keluargas = pagy(@q.result(distinct: false),items:20) 
    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=NamaKeluarga.xlsx"
      }
      format.html { render :index }
    end
  end

  def new
    @nama_keluarga = NamaKeluarga.new
    @nama_keluarga.anggota_keluargas.build
  end

  def edit

  end

  def create
    @nama_keluarga = NamaKeluarga.new(nama_keluarga_params)

      if @nama_keluarga.save
        @nama_keluarga.daftar_ulang_tahun_pernikahan
      	redirect_to admins_nama_keluargas_path, notice: 'Nama Keluarga berhasil dibuat'
      else
        render 'new'
      end
  end

  def update
    respond_to do |format|
      if @nama_keluarga.update(nama_keluarga_params)
        @nama_keluarga.daftar_ulang_tahun_pernikahan
        format.html { redirect_to admins_nama_keluargas_path, notice: 'Nama Keluarga berhasil Diupdate.' }
        format.json { render :show, status: :ok, location: @nama_keluarga }
      else
        format.html { render :edit }
        format.json { render json: @nama_keluarga.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def nama_keluarga_params
    params.require(:nama_keluarga).permit(
      :nama, :nomor_kartu_keluarga, :kolom, :active, 
      :tanggal_pernikahan, :ulang_tahun_pernikahan_aktif,
      anggota_keluargas_attributes: [
        :id, :nama, :jenis_kelamin, :nik, 
        :tanggal_lahir, :tempat_lahir, 
        :baptis, :sidi, :status_hubungan, :status_perkawinan, :_destroy]
    )
  end

  def set_nama_keluarga
    @nama_keluarga = NamaKeluarga.find(params[:id])
  end
end

app/helpers/nama_keluargas_helper.rb
module NamaKeluargasHelper
end

app/views/admins/nama_keluargas/_anggota_keluarga_fields.html.erb
<div class="col-lg-12">
  <div class = "nested-fields">
    <% if f.object.meninggal?%>
      <div class="row">
        <div class="col-lg-4">
          <%= f.input :nama, disabled:true %>
        </div>
        <div class="col-lg-4">
          <%= f.input :nik, disabled:true %>
        </div>
        <div class="col-lg-4">
          <%= f.input :jenis_kelamin, include_blank: "Pilih :", collection: AnggotaKeluarga.jenis_kelamins.keys.map { |w| [w.humanize, w] }, disabled:true%>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-6">
          <%= f.input :tempat_lahir, disabled:true%>
        </div>
        <div class="col-lg-6">
          <%= f.input :tanggal_lahir, start_year: 1901, end_year: Time.now.year, order: [:day, :month, :year], disabled:true%>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-6">
          <%= f.input :status_hubungan, include_blank: "Pilih :", disabled:true, collection: AnggotaKeluarga.status_hubungans.keys.map { |w| [w.humanize, w] }%>
        </div>
        <div class="col-lg-6">
          <%= f.input :status_perkawinan, include_blank: "Pilih :", disabled:true, collection: AnggotaKeluarga.status_perkawinans.keys.map { |w| [w.humanize, w] }%>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-6">
          <%= f.input :baptis, include_blank: "Pilih :", disabled:true, collection: AnggotaKeluarga::BAPTIS_SIDI_OPTIONS%>
        </div>
        <div class="col-lg-6">
          <%= f.input :sidi, include_blank: "Pilih :", disabled:true, collection: AnggotaKeluarga::BAPTIS_SIDI_OPTIONS%>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-10 col-md-12">
          <%=f.input :tanggal_meninggal, as: :string, disabled:true, :input_html =>{ value: l(f.object.tanggal_meninggal)}%>
        </div>
        <div class="col-lg-2">
          <%= link_to_remove_association f , class: "btn btn-sm btn-danger remove-association" do %>
            <i class="fas fa-trash-alt"></i>
          <%end%>  
        </div>
      </div>
    <%else%>
    <div class="row">
        <div class="col-lg-4">
          <%= f.input :nama %>
        </div>
        <div class="col-lg-4">
          <%= f.input :nik %>
        </div>
        <div class="col-lg-4">
          <%= f.input :jenis_kelamin, include_blank: "Pilih :", collection: AnggotaKeluarga.jenis_kelamins.keys.map { |w| [w.humanize, w] }%>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-6">
          <%= f.input :tempat_lahir%>
        </div>
        <div class="col-lg-6">
          <%= f.input :tanggal_lahir, start_year: 1901, end_year: Time.now.year, order: [:day, :month, :year]%>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-6">
          <%= f.input :status_hubungan, include_blank: "Pilih :", collection: AnggotaKeluarga.status_hubungans.keys.map { |w| [w.humanize, w] }%>
        </div>
        <div class="col-lg-6">
          <%= f.input :status_perkawinan, include_blank: "Pilih :", collection: AnggotaKeluarga.status_perkawinans.keys.map { |w| [w.humanize, w] }%>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-5">
          <%= f.input :baptis, include_blank: "Pilih :", collection: AnggotaKeluarga::BAPTIS_SIDI_OPTIONS%>
        </div>
        <div class="col-lg-5">
          <%= f.input :sidi, include_blank: "Pilih :", collection: AnggotaKeluarga::BAPTIS_SIDI_OPTIONS%>
        </div>
        <div class="col-lg-2">
          <%= link_to_remove_association f , class: "btn btn-sm btn-danger remove-association" do %>
            <i class="fas fa-trash-alt"></i>
          <%end%>  
        </div>
      </div>
    <%end%>
  </div>
</div>
    <hr class="divider">

app/views/admins/nama_keluargas/_form.html.erb
<div class="container-fluid">  
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary"><%=params[:action].capitalize%> Keluarga</h6>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-12">
          <%= simple_form_for [:admins, @nama_keluarga] do |f| %>
            <div class="row">
              <div class="col-lg-6 col-md-12">
                <%= f.input :nama %>
              </div>
              <div class="col-lg-6 col-md-12">
                <%= f.input :nomor_kartu_keluarga %>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-6 col-md-12">
                <%= f.input :kolom, include_blank: "Pilih :", :collection => Kolom.all,:label_method => :nama,
                :value_method => :nama,:label => "Kolom"  %>
              </div>
              <div class="col-lg-6">
                <%= f.input :tanggal_pernikahan, start_year: 1901, end_year: Time.now.year, order: [:day, :month, :year]%>
              </div>
              <div class="col-lg-6 col-md-12">
                <%= f.input :active, label: "Keluarga Aktif", :input_html => { :checked => true } %>
              </div>
              <div class="col-lg-12">
               <h6 class="m-0 font-weight-bold text-primary">Data Anggota Keluarga :</h6>
                <br>
              </div>  
                <div class="col-lg-12">
                  <%= f.simple_fields_for :anggota_keluargas do |anggota|%>
                    <%= render 'anggota_keluarga_fields', f: anggota%>
                  <%end%>
                  <div class="links">
                    <%= link_to_add_association 'Tambah Anggota', f, :anggota_keluargas, class: "btn btn-sm btn-success"%>
                  </div>
                  <br>
              </div>       
            </div>
              <%= f.button :submit, class: "btn btn-info" %>
              <%= link_to "Cancel", admins_nama_keluargas_path, class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/nama_keluargas/edit.html.erb
<%= render 'form'%>

app/views/admins/nama_keluargas/index.html.erb
<div class="container-fluid">
    <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Nama Keluarga</h6>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-3 col-md-12">
          <%=link_to new_admins_nama_keluarga_path, class: "btn btn-success with-margin col-md-12" do%>
            <i class="fas fa-plus"></i> Tambah Data Keluarga
          <%end%>
          <br>
        </div>
        <div class="col-lg-6 col-md-12">
          <%= search_form_for @q, url: admins_nama_keluargas_path do |f| %>               
            <div class="row">
              <div class="col-lg-9 col-md-12">
                <%= f.search_field :nama_cont, placeholder: "Cari Nama", class: 'form-control admin-search col-12 with-margin' %>
              </div>            
              <div class="col-lg-3 col-md-12">
                <%= f.button :Search, class: "btn btn-success col-lg-12 with-margin" do%>    
                <i class="fas fa-search"></i> Search
              <%end%>    
              </div>  
            </div>
          <%end%>
        </div>
        <div class="col-lg-3 col-md-12">
          <%=link_to admins_nama_keluargas_path(format: :xlsx), class: "btn btn-success with-margin col-md-12" do%>
            <i class="fas fa-download"></i> Download Data Excel
          <%end%>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama Keluarga</th>
                <th>Nomor Keluarga</th>
                <th>Kolom</th>
                <th>Action</th>
              </tr>
            </thead>
              <%@nama_keluargas.each_with_index do |nama,index|%>
                <tbody>
                  <td><%=index+1%></td>
                  <td><%=nama.nama%></td>
                  <td><%=nama.nomor_kartu_keluarga%></td>
                  <td><%=nama.kolom%></td>
                  <td>
                  <div class="row">
                  <div class="col-lg-2">
                    <%=link_to edit_admins_nama_keluarga_path(nama), class: "btn btn-sm btn-success" do%>
                      <i class="fas fa-edit"></i>
                    <%end%>
                  </div>
                  <div class="col-lg-2">
                    <%=link_to admins_nama_keluarga_path(nama), class: "btn btn-sm btn-primary" do%>
                      <i class="fas fa-eye"></i>
                    <%end%>
                  </div>
                  </div>
                  </td>
                </tbody>
              <%end%>
          </table>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/admins/nama_keluargas/new.html.erb
<%= render 'form'%>

app/views/admins/nama_keluargas/show.html.erb
ini halaman show