config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    devise_scope :user do
      root to: "devise/sessions#new"
    end
 
    #Route Admin
    namespace :admins do
      get 'dashboard' => 'pages#index'
      resources :nama_keluargas, except: [:destroy]
      resources :anggota_keluargas_imports, only: [:new, :create]
      resources :anggota_keluargas do
        collection do
          get 'pkb'
          get 'wki'
          get 'pemuda'
          get 'remaja'
          get 'asm'
          get 'template'
        end
        member do
          patch 'set_meninggal'
        end
      end
      resources :users, only: [:edit,:update] do
        member do
          patch 'change_password'
        end
      end
      resources :koloms
      resources :keuangans
      get 'meninggal_tahun_ini' => 'data_lain_lains#meninggal_tahun_ini'
      get 'lahir_tahun_ini' => 'data_lain_lains#lahir_tahun_ini'
      get 'ulang_tahun_minggu_depan' => 'data_lain_lains#ulang_tahun_minggu_depan'
      get 'ulang_tahun_minggu_ini' => 'data_lain_lains#ulang_tahun_minggu_ini'
      
    end

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                            placeholder="Search for..." aria-label="Search"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>
        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">ADMIN SION</span>
                <%=image_tag('undraw_profile.svg', :class => "img-profile rounded-circle")%>
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="<%=edit_user_path(current_user.id)%>">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Ganti Password
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Keluar
                </a>
            </div>
        </li>

    </ul>

</nav>

app/views/shared/_navbar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <a class="sidebar-brand d-flex align-items-center justify-content-center" >
        <div class="sidebar-brand-icon">
            <i class="fas fa-church"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SionerZ</div>
    </a>
    <hr class="sidebar-divider my-0">

    <li class="nav-item active">
      <%=link_to dashboard_path, class: "nav-link" do%>
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
      <%end%>
    </li>

    <li class="nav-item active">
      <%=link_to nama_keluargas_path, class: "nav-link" do%>
            <i class="fas fa-users"></i>
            <span>Nama Keluarga</span></a>
      <%end%>
    </li>
    <li class="nav-item">
        <a class="nav-link collapsed" href="" data-toggle="collapse" data-target="#collapseTwo"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-user"></i>
            <span>Daftar Anggota</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="<%=anggota_keluargas_path%>">Semua Data</a>
                <a class="collapse-item" href="<%=pkb_anggota_keluargas_path%>">PKB</a>
                <a class="collapse-item" href="<%=wki_anggota_keluargas_path%>">WKI</a>
                <a class="collapse-item" href="<%=pemuda_anggota_keluargas_path%>">Pemuda</a>
                <a class="collapse-item" href="<%=remaja_anggota_keluargas_path%>">Remaja</a>
                <a class="collapse-item" href="<%=asm_anggota_keluargas_path%>">ASM</a>
            </div>
        </div>
    </li>
    <li class="nav-item active">
      <%=link_to koloms_path, class: "nav-link" do%>
            <i class="fas fa-church"></i>
            <span>Kolom</span></a>
      <%end%>
    </li>
    <hr class="sidebar-divider">
    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
          aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-birthday-cake"></i> 
          <span>Ulang Tahun</span>
      </a>
      <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
          data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
              <a class="collapse-item" href="<%=ulang_tahun_minggu_ini_anggota_keluargas_path%>">Minggu Ini</a>
              <a class="collapse-item" href="<%=ulang_tahun_minggu_depan_anggota_keluargas_path%>">Minggu Depan</a>
          </div>
      </div>  
  </li>

  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
        aria-expanded="true" aria-controls="collapsePages">
        <i class="fas fa-stream"></i>
        <span>Data Lain - Lain</span>
    </a>
    <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="<%=lahir_tahun_ini_anggota_keluargas_path%>">Kelahiran Tahun Ini</a>
            <a class="collapse-item" href="<%=meninggal_tahun_ini_anggota_keluargas_path%>">Kematian Tahun Ini</a>
        </div>
    </div>
</li>
</ul>