config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    devise_scope :user do
      root to: "devise/sessions#new"
    end
 
    #Route Admin
    namespace :admins do
      get 'dashboard' => 'pages#index'
      resources :nama_keluargas, except: [:destroy]
      resources :anggota_keluargas_imports, only: [:new, :create]
      resources :anggota_keluargas do
        collection do
          get 'pkb'
          get 'wki'
          get 'pemuda'
          get 'remaja'
          get 'asm'
          get 'template'
        end
        member do
          patch 'set_meninggal'
        end
      end
      resources :users, only: [:edit,:update] do
        member do
          patch 'change_password'
        end
      end
      resources :koloms
      resources :keuangans
      get 'meninggal_tahun_ini' => 'data_lain_lains#meninggal_tahun_ini'
      get 'lahir_tahun_ini' => 'data_lain_lains#lahir_tahun_ini'
      get 'ulang_tahun_minggu_depan' => 'data_lain_lains#ulang_tahun_minggu_depan'
      get 'ulang_tahun_minggu_ini' => 'data_lain_lains#ulang_tahun_minggu_ini'
      
    end

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/views/admins/shared/_bootstrap_nav.html.erb
<%#
  This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
  calls with the actual strings ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;").

  The link variable is set to a proc that returns the link tag.
  Usage: link.call( page_number [, text [, extra_attributes_string ]])
-%>
<% link = pagy_link_proc(pagy, 'class="page-link"') -%>
<%#                            -%><nav aria-label="pager"  class="pagy-bootstrap-nav" role="navigation">
<%#                            -%>  <ul class="pagination">
<% if pagy.prev                -%>    <li class="page-item prev"><%== link.call(pagy.prev, pagy_t('pagy.nav.prev'), 'aria-label="previous"') %></li>
<% else                        -%>    <li class="page-item prev disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.prev') %></a></li>
<% end                         -%>
<% pagy.series.each do |item| # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36] -%>
<%   if    item.is_a?(Integer) -%>    <li class="page-item"><%== link.call(item) %></li>
<%   elsif item.is_a?(String)  -%>    <li class="page-item active"><%== link.call(item) %></li>
<%   elsif item == :gap        -%>    <li class="page-item disabled gap"><a href="#" class="page-link"><%== pagy_t('pagy.nav.gap') %></a></li>
<%   end                       -%>
<% end                         -%>
<% if pagy.next                -%>    <li class="page-item next"><%== link.call(pagy.next, pagy_t('pagy.nav.next'), 'aria-label="next"') %></li>
<% else                        -%>    <li class="page-item next disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.next') %></a></li>
<% end                         -%>
<%#                            -%>  </ul>
<%#                            -%></nav>

app/views/admins/shared/_footer.html.erb
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Made with &#128150; <br>Copyright &copy; Omega <%=Date.today.year%></span>
        </div>
    </div>
</footer>

app/views/admins/shared/_header.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  <ul class="navbar-nav ml-auto">
    <div class="topbar-divider d-none d-sm-block"></div>  
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="mr-2 d-none d-lg-inline text-gray-600 small">ADMIN SION</span>
            <%=image_tag('undraw_profile.svg', :class => "img-profile rounded-circle")%>
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
            aria-labelledby="userDropdown">
          <%= link_to change_password_admins_user_path(current_user.id), method: :patch, class: "dropdown-item" do %>
            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
              Ganti Password
          <%end%>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
              <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
              Keluar
          </a>
        </div>
      </li>

  </ul>
</nav>

app/views/admins/shared/_navbar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <a class="sidebar-brand d-flex align-items-center justify-content-center" >
        <div class="sidebar-brand-icon">
            <i class="fas fa-church"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SionerZ</div>
    </a>
    <hr class="sidebar-divider my-0">

    <li class="nav-item active">
      <%=link_to admins_dashboard_path, class: "nav-link" do%>
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
      <%end%>
    </li>

    <li class="nav-item active">
      <%=link_to admins_nama_keluargas_path, class: "nav-link" do%>
            <i class="fas fa-users"></i>
            <span>Data Nama Keluarga</span></a>
      <%end%>
    </li>

    <li class="nav-item active">
      <%=link_to admins_anggota_keluargas_path, class: "nav-link" do%>
            <i class="fas fa-user"></i>
            <span>Data Anggota Jemaat</span></a>
      <%end%>
    </li>
    <li class="nav-item">
        <a class="nav-link collapsed" href="" data-toggle="collapse" data-target="#collapseTwo"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-user"></i>
            <span>Data BIPRA</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="<%=pkb_admins_anggota_keluargas_path%>">PKB</a>
                <a class="collapse-item" href="<%=wki_admins_anggota_keluargas_path%>">WKI</a>
                <a class="collapse-item" href="<%=pemuda_admins_anggota_keluargas_path%>">Pemuda</a>
                <a class="collapse-item" href="<%=remaja_admins_anggota_keluargas_path%>">Remaja</a>
                <a class="collapse-item" href="<%=asm_admins_anggota_keluargas_path%>">ASM</a>
            </div>
        </div>
    </li>

      <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
          aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-birthday-cake"></i> 
          <span>Ulang Tahun</span>
      </a>
      <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
          data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
              <a class="collapse-item" href="<%=admins_ulang_tahun_minggu_ini_path%>">Minggu Ini</a>
              <a class="collapse-item" href="<%=admins_ulang_tahun_minggu_depan_path%>">Minggu Depan</a>
          </div>
      </div>  
  </li>

  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
        aria-expanded="true" aria-controls="collapsePages">
        <i class="fas fa-stream"></i>
        <span>Data Lain - Lain</span>
    </a>
    <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="<%=admins_lahir_tahun_ini_path%>">Kelahiran Tahun Ini</a>
            <a class="collapse-item" href="<%=admins_meninggal_tahun_ini_path%>">Kematian Tahun Ini</a>
        </div>
    </div>
  </li>

  <hr class="sidebar-divider">
  <li class="nav-item active">
    <%=link_to admins_koloms_path, class: "nav-link" do%>
          <i class="fas fa-church"></i>
          <span>Kolom</span></a>
    <%end%>
  </li>
</ul>