config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    devise_scope :user do
      root to: "devise/sessions#new"
    end
 
    #Route Admin
    namespace :admins do
      get 'dashboard' => 'pages#index'
      resources :nama_keluargas, except: [:destroy]
      resources :anggota_keluargas_imports, only: [:new, :create]
      resources :anggota_keluargas do
        collection do
          get 'pkb'
          get 'wki'
          get 'pemuda'
          get 'remaja'
          get 'asm'
          get 'template'
        end
        member do
          patch 'set_meninggal'
        end
      end
      resources :users, only: [:edit,:update] do
        member do
          patch 'change_password'
        end
      end
      resources :koloms
      resources :keuangans
      get 'meninggal_tahun_ini' => 'data_lain_lains#meninggal_tahun_ini'
      get 'lahir_tahun_ini' => 'data_lain_lains#lahir_tahun_ini'
      get 'ulang_tahun_minggu_depan' => 'data_lain_lains#ulang_tahun_minggu_depan'
      get 'ulang_tahun_minggu_ini' => 'data_lain_lains#ulang_tahun_minggu_ini'
      
    end

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/anggota_keluarga.rb
# == Schema Information
#
# Table name: anggota_keluargas
#
#  id                :bigint           not null, primary key
#  baptis            :integer
#  jenis_kelamin     :integer
#  meninggal         :boolean          default(FALSE)
#  nama              :string
#  nik               :string
#  sidi              :integer
#  status_hubungan   :integer
#  status_perkawinan :integer
#  tanggal_lahir     :date
#  tanggal_meninggal :date
#  tempat_lahir      :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  nama_keluarga_id  :bigint           not null
#
# Indexes
#
#  index_anggota_keluargas_on_nama_keluarga_id  (nama_keluarga_id)
#
# Foreign Keys
#
#  fk_rails_...  (nama_keluarga_id => nama_keluargas.id)
#
class AnggotaKeluarga < ApplicationRecord
  belongs_to :nama_keluarga

  #validate
  validates :nama, :presence => true,
    :on => [:update, :create]
  validates :jenis_kelamin, :presence => true,
    :on => [:update, :create]
  validates :tempat_lahir, :presence => true,
    :on => [:update, :create]
  validates :tanggal_lahir, :presence => true,
    :on => [:update, :create]
  validates :status_perkawinan, :presence => true,
    :on => [:update, :create]
  validates :status_hubungan, :presence => true,
    :on => [:update, :create]
  validates :baptis, :presence => true,
    :on => [:update, :create]
  validates :sidi, :presence => true,
    :on => [:update, :create]


  enum jenis_kelamin: {pria: 1, wanita: 2}
  enum status_hubungan: {kepala_keluarga: 1, istri: 2, anak: 3, orang_tua: 4}
  enum status_perkawinan: {kawin: 1, belum_kawin: 2, cerai_hidup: 3, cerai_mati: 4}
  
  
  #Scope Kategorial
  scope :pkb, ->{where('jenis_kelamin = ? and status_perkawinan != ? and meninggal = ?',1,2,false)}
  scope :wki, ->{where('jenis_kelamin = ? and status_perkawinan != ? and meninggal = ?',2,2,false)}
  scope :pemuda, ->{where("status_perkawinan = ? and date_part('year', age(tanggal_lahir)) >= ? AND date_part('year', age(tanggal_lahir)) <= ?  and meninggal = ?",2,17,35,false)}
  scope :remaja, ->{where("status_perkawinan = ? and date_part('year', age(tanggal_lahir)) >= ? AND date_part('year', age(tanggal_lahir)) <= ?  and meninggal = ?",2,12,17,false)}
  scope :asm, ->{where("status_perkawinan = ? and date_part('year', age(tanggal_lahir)) >= ? AND date_part('year', age(tanggal_lahir)) <= ?  and meninggal = ?",2,0,11,false)}
  
  #Scope Ulang Tahun
  scope :ulang_tahun, ->(mulai_bulan, selesai_bulan, mulai_tanggal, selesai_tanggal){where("EXTRACT(month FROM tanggal_lahir) >= ? AND EXTRACT(month FROM tanggal_lahir) <= ? AND EXTRACT(day FROM tanggal_lahir) >= ? AND EXTRACT(day FROM tanggal_lahir) <= ?  and meninggal = ?",mulai_bulan,selesai_bulan,mulai_tanggal,selesai_tanggal,false )}
  scope :lahir_tahun_ini, ->{where("tanggal_lahir >= ? AND tanggal_lahir <= ?",Date.today.beginning_of_year, Date.today.end_of_year)}
  scope :meninggal_tahun_ini, ->{where("tanggal_meninggal >= ? AND tanggal_meninggal <= ? AND meninggal = ?",Date.today.beginning_of_year, Date.today.end_of_year,true)}

  BAPTIS_SIDI_OPTIONS = [
    ["Sudah", 1],
    ["Belum", 2]
  ]

  def baptis_sidi_list
    BAPTIS_SIDI_OPTIONS.map do |x,y|
      {
       :id => y,
       :name => x
      }
    end
  end

  #Mencari Umur
  def umur
    now = Date.today
    now.year - tanggal_lahir.year - ((now.month > tanggal_lahir.month || (now.month == tanggal_lahir.month && now.day >= tanggal_lahir.day)) ? 0 : 1)
  end
end

app/controllers/admins/anggota_keluargas_controller.rb
class Admins::AnggotaKeluargasController < AdminsController
  before_action :set_anggota_keluarga, only: [:set_meninggal]
  def index
    @q = AnggotaKeluarga.where(meninggal: false).includes(:nama_keluarga).order("nama_keluarga.kolom::integer asc, nama_keluarga.id desc").ransack(params[:q])
    @pagy, @anggota_keluargas = pagy(@q.result(distinct: false),items:20)
    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=Semua Anggota.xlsx"
      }
      format.html { render :index }
    end
  end

  def template
    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=Template Import Anggota.xlsx"
      }
      format.html { render :index }
    end
  end

  def pkb
    @q = AnggotaKeluarga.pkb.includes(:nama_keluarga).order("nama_keluarga.kolom::integer asc").ransack(params[:q])
		@pagy, @anggota_keluargas = pagy(@q.result(distinct: false),items:20)
    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=Anggota PKB.xlsx"
      }
      format.html { render :pkb }
    end
  end

  def wki
    @q = AnggotaKeluarga.wki.includes(:nama_keluarga).order("nama_keluarga.kolom::integer asc").ransack(params[:q])
		@pagy, @anggota_keluargas = pagy(@q.result(distinct: false),items:20)
    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=Anggota WKI.xlsx"
      }
      format.html { render :wki }
    end
  end

  def pemuda
    @q = AnggotaKeluarga.pemuda.includes(:nama_keluarga).order("nama_keluarga.kolom::integer asc").ransack(params[:q])
		@pagy, @anggota_keluargas = pagy(@q.result(distinct: false),items:20)
    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=Anggota Pemuda.xlsx"
      }
      format.html { render :pemuda }
    end
  end

  def remaja
    @q = AnggotaKeluarga.remaja.includes(:nama_keluarga).order("nama_keluarga.kolom::integer asc").ransack(params[:q])
		@pagy, @anggota_keluargas = pagy(@q.result(distinct: false),items:20)
    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=Anggota Remaja.xlsx"
      }
      format.html { render :remaja }
    end
  end

  def asm
    @q = AnggotaKeluarga.asm.includes(:nama_keluarga).order("nama_keluarga.kolom::integer asc").ransack(params[:q])
		@pagy, @anggota_keluargas = pagy(@q.result(distinct: false),items:20)
    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=Anggota Anak Sekolah Minggu.xlsx"
      }
      format.html { render :asm }
    end
  end

  
  def set_meninggal
    @anggota_keluarga.update(tanggal_meninggal: Date.today, meninggal: true)
    if @anggota_keluarga.nama_keluarga.anggota_keluargas.pluck(:meninggal).exclude? false
      @anggota_keluarga.nama_keluarga.update(active: false)
    end
    redirect_to admins_anggota_keluargas_path, notice: 'Data Anggota berhasil Diupdate.' 
  end
  
  private

   def set_anggota_keluarga
    @anggota_keluarga = AnggotaKeluarga.find(params[:id])
   end

end

app/helpers/anggota_keluargas_helper.rb
module AnggotaKeluargasHelper
end

app/views/admins/anggota_keluargas/asm.html.erb
<div class="container-fluid">
    <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Daftar Anak Sekolah Minggu</h6>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-9">
        <%= search_form_for @q, url: asm_admins_anggota_keluargas_path do |f| %>               
          <div class="row">
            <div class="col-lg-6 col-md-12">
              <%= f.search_field :nama_cont, placeholder: "Cari Nama", class: 'form-control admin-search  col-12 with-margin' %>
            </div>
            <div class="col-lg-6 col-md-12">
              <%= f.button :Search, class: "btn btn-success col-lg-6 col-md-12 with-margin" do%>    
                <i class="fas fa-search"></i> Search
              <%end%> 
            </div> 
          </div>
        <%end%>
        </div>
        <div class="col-lg-3">
        <%=link_to asm_admins_anggota_keluargas_path(format: :xlsx), class: "btn btn-success col-md-12 with-margin" do%>
            <i class="fas fa-download"></i> Download Data Excel
          <%end%>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama Anggota</th>
                <th>Umur</th>
                <th>Keluarga</th>
                <th>Kolom</th>
              </tr>
            </thead>
              <%@anggota_keluargas.each_with_index do |anggota,index|%>
                <tbody>
                  <td><%=index+1%></td>
                  <td><%=anggota.nama.humanize%></td>
                  <td><%=anggota.umur%> Tahun</td>
                  <td><%=anggota.nama_keluarga.nama%></td>
                  <td><%=anggota.nama_keluarga.kolom%></td>
                  
                </tbody>
              <%end%>
          </table>
            <%== render partial: 'shared/bootstrap_nav', locals: {pagy: @pagy} %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/admins/anggota_keluargas/index.html.erb
<div class="container-fluid">
    <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Daftar Anggota</h6>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-6 col-md-12">
        <%= search_form_for @q, url: admins_anggota_keluargas_path do |f| %>               
          <div class="row">
            <div class="col-lg-6 col-md-12">
              <%= f.search_field :nama_cont, placeholder: "Cari Nama", class: 'form-control admin-search  col-12 with-margin' %>
            </div>
            <div class="col-lg-6 col-md-12">
              <%= f.button :Search, class: "btn btn-success col-lg-6 col-md-12 with-margin" do%>    
                <i class="fas fa-search"></i> Search
              <%end%> 
            </div>  
          </div>
        <%end%>
        </div>
        <div class="col-lg-3 col-md-12">
        <%=link_to admins_anggota_keluargas_path(format: :xlsx), class: "btn btn-success col-md-12 with-margin" do%>
            <i class="fas fa-download"></i> Download Data Excel
          <%end%>
        </div>
        <div class="col-lg-3 col-md-12">
        <%=link_to new_admins_anggota_keluargas_import_path, class: "btn btn-success col-md-12 with-margin" do%>
            <i class="fas fa-upload"></i> Upload Dari Excel
          <%end%>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama Anggota</th>
                <th>Umur</th>
                <th>Keluarga</th>
                <th>Kolom</th>
                <th></th>
              </tr>
            </thead>
              <%@anggota_keluargas.each_with_index do |anggota,index|%>
                <tbody>
                  <td><%=index+1%></td>
                  <td><%=anggota.nama.humanize%></td>
                  <td><%=anggota.umur%> Tahun</td>
                  <td><%=anggota.nama_keluarga.nama%></td>
                  <td><%=anggota.nama_keluarga.kolom%></td>
                  <td>
                   <div class="row">
                      <div class="col-lg-2">
                        <%=link_to set_meninggal_admins_anggota_keluarga_path(anggota.id), class: "btn btn-sm btn-danger", method: :patch, data: { confirm: "Anda Yakin ?"} do%>
                          Meninggal?
                        <%end%>
                      </div>  
                    </div>
                  </td>
                </tbody>
              <%end%>
          </table>
            <%== render partial: 'shared/bootstrap_nav', locals: {pagy: @pagy} %>
          </div>
      </div>
    </div>
  </div>

</div>

app/views/admins/anggota_keluargas/meninggal_tahun_ini.html.erb
<div class="container-fluid">
    <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Daftar Kematian Tahun <%=Date.today.year%></h6>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-3">
        </div>
        <div class="col-lg-6">
        </div>
        <div class="col-lg-3">
        <%=link_to meninggal_tahun_ini_admins_anggota_keluargas_path(format: :xlsx), class: "btn btn-sm btn-success col-md-12 with-margin" do%>
            <i class="fas fa-download"></i> Download Data Excel
          <%end%>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama Anggota</th>
                <th>Lahir Tanggal</th>
                <th>Keluarga</th>
                <th>Kolom</th>
              </tr>
            </thead>
              <%@anggota_keluargas.each_with_index do |anggota,index|%>
                <tbody>
                  <td><%=index+1%></td>
                  <td><%=anggota.nama.humanize%></td>
                  <td><%=anggota.tanggal_meninggal.strftime("%d %b %Y")%></td>
                  <td><%=anggota.nama_keluarga.nama%></td>
                  <td><%=anggota.nama_keluarga.kolom%></td>
                  
                </tbody>
              <%end%>
          </table>
            <%== render partial: 'shared/bootstrap_nav', locals: {pagy: @pagy} %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/admins/anggota_keluargas/pemuda.html.erb
<div class="container-fluid">
    <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Daftar Pemuda</h6>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-9">
        <%= search_form_for @q, url: pemuda_admins_anggota_keluargas_path do |f| %>               
          <div class="row">
            <div class="col-lg-6 col-md-12">
              <%= f.search_field :nama_cont, placeholder: "Cari Nama", class: 'form-control admin-search  col-12 with-margin' %>
            </div>
            <div class="col-lg-6 col-md-12">
              <%= f.button :Search, class: "btn btn-success col-lg-6 col-md-12 with-margin" do%>    
                <i class="fas fa-search"></i> Search
              <%end%> 
            </div> 
          </div>
        <%end%>
        </div>
        <div class="col-lg-3">
        <%=link_to pemuda_admins_anggota_keluargas_path(format: :xlsx), class: "btn btn-success col-md-12 with-margin" do%>
            <i class="fas fa-download"></i> Download Data Excel
          <%end%>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama Anggota</th>
                <th>Umur</th>
                <th>Keluarga</th>
                <th>Kolom</th>
              </tr>
            </thead>
              <%@anggota_keluargas.each_with_index do |anggota,index|%>
                <tbody>
                  <td><%=index+1%></td>
                  <td><%=anggota.nama.humanize%></td>
                  <td><%=anggota.umur%> Tahun</td>
                  <td><%=anggota.nama_keluarga.nama%></td>
                  <td><%=anggota.nama_keluarga.kolom%></td>
                  
                </tbody>
              <%end%>
          </table>
            <%== render partial: 'shared/bootstrap_nav', locals: {pagy: @pagy} %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/admins/anggota_keluargas/pkb.html.erb
<div class="container-fluid">
    <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Daftar PKB</h6>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-9">
        <%= search_form_for @q, url: pkb_admins_anggota_keluargas_path do |f| %>               
          <div class="row">
            <div class="col-lg-6 col-md-12">
              <%= f.search_field :nama_cont, placeholder: "Cari Nama", class: 'form-control admin-search  col-12 with-margin' %>
            </div>
            <div class="col-lg-6 col-md-12">
              <%= f.button :Search, class: "btn btn-success col-lg-6 col-md-12 with-margin" do%>    
                <i class="fas fa-search"></i> Search
              <%end%> 
            </div>  
          </div>
        <%end%>
        </div>
        <div class="col-lg-3">
        <%=link_to pkb_admins_anggota_keluargas_path(format: :xlsx), class: "btn btn-success col-md-12 with-margin" do%>
            <i class="fas fa-download"></i> Download Data Excel
          <%end%>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama Anggota</th>
                <th>Umur</th>
                <th>Keluarga</th>
                <th>Kolom</th>
              </tr>
            </thead>
              <%@anggota_keluargas.each_with_index do |anggota,index|%>
                <tbody>
                  <td><%=index+1%></td>
                  <td><%=anggota.nama.humanize%></td>
                  <td><%=anggota.umur%> Tahun</td>
                  <td><%=anggota.nama_keluarga.nama%></td>
                  <td><%=anggota.nama_keluarga.kolom%></td>
                  
                </tbody>
              <%end%>
          </table>
            <%== render partial: 'shared/bootstrap_nav', locals: {pagy: @pagy} %>
          </div>
      </div>
    </div>
  </div>

</div>

app/views/admins/anggota_keluargas/remaja.html.erb
<div class="container-fluid">
    <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Daftar Remaja</h6>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-9">
        <%= search_form_for @q, url: remaja_admins_anggota_keluargas_path do |f| %>               
          <div class="row">
            <div class="col-lg-6 col-md-12">
              <%= f.search_field :nama_cont, placeholder: "Cari Nama", class: 'form-control admin-search  col-12 with-margin' %>
            </div>
            <div class="col-lg-6 col-md-12">
              <%= f.button :Search, class: "btn btn-success col-lg-6 col-md-12 with-margin" do%>    
                <i class="fas fa-search"></i> Search
              <%end%> 
            </div> 
          </div>
        <%end%>
        </div>
        <div class="col-lg-3">
        <%=link_to remaja_admins_anggota_keluargas_path(format: :xlsx), class: "btn btn-success col-md-12 with-margin" do%>
            <i class="fas fa-download"></i> Download Data Excel
          <%end%>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama Anggota</th>
                <th>Umur</th>
                <th>Keluarga</th>
                <th>Kolom</th>
              </tr>
            </thead>
              <%@anggota_keluargas.each_with_index do |anggota,index|%>
                <tbody>
                  <td><%=index+1%></td>
                  <td><%=anggota.nama.humanize%></td>
                  <td><%=anggota.umur%> Tahun</td>
                  <td><%=anggota.nama_keluarga.nama%></td>
                  <td><%=anggota.nama_keluarga.kolom%></td>
                  
                </tbody>
              <%end%>
          </table>
            <%== render partial: 'shared/bootstrap_nav', locals: {pagy: @pagy} %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/admins/anggota_keluargas/ulang_tahun_minggu_depan.html.erb
<div class="container-fluid">
    <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Jemaat yang Berulang Tahun Tanggal <%=(Date.today+7).beginning_of_week.strftime("%d") + " - " + (Date.today+7).end_of_week.strftime("%d %b %Y")%></h6>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-3">
        </div>
        <div class="col-lg-6">
        </div>
        <div class="col-lg-3">
        <%=link_to ulang_tahun_minggu_depan_admins_anggota_keluargas_path(format: :xlsx), class: "btn btn-success col-md-12 with-margin" do%>
            <i class="fas fa-download"></i> Download Data Excel
          <%end%>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama Anggota</th>
                <th>Umur Ke</th>
                <th>Keluarga</th>
                <th>Kolom</th>
              </tr>
            </thead>
              <%@anggota_keluargas.each_with_index do |anggota,index|%>
                <tbody>
                  <td><%=index+1%></td>
                  <td><%=anggota.nama.humanize%></td>
                  <td><%=anggota.umur + 1%> Tahun</td>
                  <td><%=anggota.nama_keluarga.nama%></td>
                  <td><%=anggota.nama_keluarga.kolom%></td>
                  
                </tbody>
              <%end%>
          </table>
            <%== render partial: 'shared/bootstrap_nav', locals: {pagy: @pagy} %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/admins/anggota_keluargas/ulang_tahun_minggu_ini.html.erb
<div class="container-fluid">
    <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Jemaat yang Berulang Tahun Tanggal <%=Date.today.beginning_of_week.strftime("%d  ") + " - " + Date.today.end_of_week.strftime("%d %b %Y")%></h6>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-3">
        </div>
        <div class="col-lg-6">
        </div>
        <div class="col-lg-3">
        <%=link_to ulang_tahun_minggu_ini_admins_anggota_keluargas_path(format: :xlsx), class: "btn btn-success col-md-12 with-margin" do%>
            <i class="fas fa-download"></i> Download Data Excel
          <%end%>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama Anggota</th>
                <th>Umur Ke</th>
                <th>Keluarga</th>
                <th>Kolom</th>
              </tr>
            </thead>
              <%@anggota_keluargas.each_with_index do |anggota,index|%>
                <tbody>
                  <td><%=index+1%></td>
                  <td><%=anggota.nama.humanize%></td>
                  <td><%=anggota.umur + 1%> Tahun</td>
                  <td><%=anggota.nama_keluarga.nama%></td>
                  <td><%=anggota.nama_keluarga.kolom%></td>
                </tbody>
              <%end%>
          </table>
            <%== render partial: 'shared/bootstrap_nav', locals: {pagy: @pagy} %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/admins/anggota_keluargas/wki.html.erb
<div class="container-fluid">
    <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Daftar WKI</h6>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-9">
        <%= search_form_for @q, url: wki_admins_anggota_keluargas_path do |f| %>               
          <div class="row">
            <div class="col-lg-6 col-md-12">
              <%= f.search_field :nama_cont, placeholder: "Cari Nama", class: 'form-control admin-search  col-12 with-margin' %>
            </div>
            <div class="col-lg-6 col-md-12">
              <%= f.button :Search, class: "btn btn-success col-lg-6 col-md-12 with-margin" do%>    
                <i class="fas fa-search"></i> Search
              <%end%> 
            </div> 
          </div>
        <%end%>
        </div>
        <div class="col-lg-3">
        <%=link_to wki_admins_anggota_keluargas_path(format: :xlsx), class: "btn btn-success col-md-12 with-margin" do%>
            <i class="fas fa-download"></i> Download Data Excel
          <%end%>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama Anggota</th>
                <th>Umur</th>
                <th>Keluarga</th>
                <th>Kolom</th>
              </tr>
            </thead>
              <%@anggota_keluargas.each_with_index do |anggota,index|%>
                <tbody>
                  <td><%=index+1%></td>
                  <td><%=anggota.nama.humanize%></td>
                  <td><%=anggota.umur%> Tahun</td>
                  <td><%=anggota.nama_keluarga.nama%></td>
                  <td><%=anggota.nama_keluarga.kolom%></td>
                  
                </tbody>
              <%end%>
          </table>
            <%== render partial: 'shared/bootstrap_nav', locals: {pagy: @pagy} %>
        </div>
      </div>
    </div>
  </div>

</div>